console.log("Hello from ts.");
var myString;
var myNum;
var myBool;
var myVar;
var strArr;
// let strArr: string[];
var numArr;
// let numArr: number[];
var booArr;
//let booArr: boolean[];
var strNumTuple;
var myNull = null;
var myVoid = undefined;
var myUndefined = undefined;
strNumTuple = ["Hello", 4];
myString = "hell world".slice(0, 3);
myNum = 0xd1;
myBool = true;
myVar = 5 + "4";
strArr = ["hello", "world", "2"];
numArr = [1, 2, 3];
booArr = [true, false, true];
console.log(myString);
console.log(myNum);
console.log(myBool);
console.log(myVar);
console.log(strArr);
console.log(numArr);
console.log(booArr);
console.log(strNumTuple);
console.log(myNull);
console.log(myVoid);
console.log(myUndefined);
